### ISSUE TITLE
Participants Restrictions

### ISSUE THREAD

**Issue by rodrimaia** [CourtHive/tods-competition-factory#1069]
I am trying to use this lib to create an app (or contribute to this one) in order to have automatic scheduling that also considers Participants Restrictions.

I mean, in my city is pretty common to have tournaments where you can let the organizers know in advance your restrictions/openings. like " I can play Thursday night, Fridays on mornings, and entire Saturdays". 

I can see that you have the restrictions feature when assigning Courts, but I would also like to add the option to have participants contribute with their restrictions too (and the automatic scheduling should use this information when assigning matchups (and possibly future matchups too)). Is that possible? I am willing to create a pull request to implement this, but it would be nice to pick your brain a little bit on where this logic should live.

and of course,  congratulations on this fantastic project!!

**Comment by CourtHive** [comment]
Rodrigo - please forgive me for not seeing this issue.  Participant "availability" is already implemented in the factory but not currently in use by USTA/ITA or any other providers who use the factory... I'd be very happy to walk you through this and see if I've missed anything.

**Comment by CourtHive** [comment]
desired functionality exists
